version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - node
      - json-server
      - templates
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  node:
    image: node:14
    command: npm start
    networks:
      - app
      - frontend
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:delegated

  cypress:
    image: cypress/included:7.5.0
    networks:
      - app
    depends_on:
      - nginx
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_baseUrl=http://nginx
      #- DISPLAY=host.docker.internal:0
    volumes:
      - .:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /e2e
    entrypoint: cypress

  json-server:
    image: node:14
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm start
    networks:
      - app
    working_dir: /app
    volumes:
      - ${PWD}/json-server:/app

  templates:
    image: node:14
    environment:
      - DEBUG=*
    command: npm start
    # @TODO: Fix setup so the ws connection between browser and webpack-dev-server can be achieved without exposing port.
    ports:
      - '3000:3000'
    networks:
      - app
    working_dir: /app
    volumes:
      - ${PWD}/templates:/app
