---
on:
  push:
    branches:
      - 'develop'
name: Build docker image (develop)

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      VERSION: alpha
      APP_VERSION: develop

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set release timestamp
        run: echo "APP_RELEASE_TIMESTAMP=$(echo $(date +%s))" >> $GITHUB_ENV

      - name: Build and push (API)
        uses: docker/build-push-action@v2
        with:
          context: ./infrastructure/
          file: ./infrastructure/Dockerfile
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
            APP_RELEASE_TIMESTAMP={{ env.APP_VERSION }}
          push: true
          tags: itkdev/os2display-client:${{ env.VERSION }}

