---
on:
  push:
    tags:
      - '*'
name: Build docker image (tag)

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set release timestamp
        run: |
          echo "APP_RELEASE_TIMESTAMP=$(echo $(date +%s))" >> $GITHUB_ENV
          echo "APP_RELEASE_TIME=$(echo $(date))" >> $GITHUB_ENV

      - name: Build and push (API)
        uses: docker/build-push-action@v2
        with:
          context: ./infrastructure/
          file: ./infrastructure/Dockerfile
          build-args: |
            APP_VERSION=${{ env.GITHUB_REF_NAME }}
            APP_RELEASE_TIMESTAMP=${{ env.APP_RELEASE_TIMESTAMP }}
            APP_RELEASE_TIME=${{ env.APP_RELEASE_TIME }}
          push: true
          tags: itkdev/os2display-client:${{ env.GITHUB_REF_NAME }}

