on:
  push:
    tags:
      - '*.*.*'

name: Create Github Release

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make build dir
        run: |
          mkdir -p build

      - name: Build assets
        run: |
          docker network create frontend
          docker compose run --rm node yarn install
          docker compose run --rm node yarn build

      - name: Create release file
        run: |
          rm build/example_release.json
          printf "{\n  \"releaseTimestamp\": $(date +%s),\n  \"releaseTime\": \"$(date)\",\n  \"releaseVersion\": \"${{ github.ref_name }}\"\n}" > build/release.json
          cat build/release.json

      - name: Rename build dir
        # Make archive directory name match expected build "homepage": "/client/",
        run: |
          mv build/ client

      - name: Make artefacts dir
        run: |
          mkdir -p ../assets

      - name: Create archive
        run: |
          tar \
            --exclude ='client/fixtures' \
            -zcf ../assets/${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz client/*

      - name: Create checksum
        run: sha256sum ../assets/${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz > ../assets/checksum.txt

      - name: Create a release in GitHub and uploads assets
        run: |
          gh release create ${{ github.ref_name }} --verify-tag --generate-notes ../assets/*.*
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
