on: pull_request
name: Review
jobs:
  frontend-build:
    name: Frontend build
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: install
        run: npm install
      - name: Build production assets
        run: npm run build

  frontend-coding-standards:
    name: Frontend coding standards
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: install
        run: npm install
      - name: React coding standards
        run: npm run check-coding-standards

  cypress-run-chrome:
    name: Cypress (Chrome)
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-build-cache
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          browser: chrome

  cypress-run-firefox:
    name: Cypress (Firefox)
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-build-cache
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          browser: firefox

  cypress-run-edge:
    name: Cypress (Edge)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-build-cache
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          browser: edge
